/**
 * enum to describe user roles
 */
export enum UserRoles {
    ADMIN = 'ADMIN',
    USER = 'USER',
    MANAGE_DEVICE = 'MANAGE_DEVICE',
    MANAGE_USERS = 'MANAGE_USERS',
    MANAGE_REQUESTS = 'MANAGE_REQUESTS',
    MANAGE_GROUPS = 'MANAGE_GROUPS',
    RESET_ANY_PASSWORD = 'RESET_ANY_PASSWORD',
    SUPERADMIN = 'SUPERADMIN',
    CAN_DELETE_USERS = 'CAN_DELETE_USERS',
    MANAGE_MODELS = 'MANAGE_MODELS',
}
